### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Jrobinson212** [Jrobinson212/prework-study-guide#1]
#HTML

## User story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework study guide website
WHEN I visit the website in my browser
THEN I see four boxes titles HTML, CSS, Git< and JavaSciript with associated notes listed

**Comment by pranesh2607** [comment]
I will be doing it for you man.
